name = "MyDMRGPkg"
uuid = "4f9e4786-5133-44db-916a-c03452369f5e"
version = "1.0.0-DEV"
authors = ["Oceanink"]

[deps]
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
KrylovKit = "0.10.2"
LinearAlgebra = "1.12.0"
Plots = "1.41.5"
Printf = "1.11.0"
Random = "1.11.0"
TensorOperations = "5.5.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
