name = "MyDMRGPkg"
uuid = "4f9e4786-5133-44db-916a-c03452369f5e"
authors = ["Oceanink"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
